#!/usr/bin/env python3

# Michjzuman's Terminal Poker

from datetime import datetime, timedelta

import time
import getpass
import asyncio

import tools
import ascii
import find_hands

user = {}

def main(intro=True):
    if intro:
        ascii.animations.intro()
    
    tools.clear()
    
    print(ascii.window(
        f"""Menu:

- Join Poker Table
"""))

if __name__ == "__main__":
    main(False)